
recipe: default.v1

language: en


# NLU PIPELINE

pipeline:
   - name: SpacyNLP
     model: en_core_web_md
   - name: SpacyTokenizer
   - name: SpacyFeaturizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: "char_wb"
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
     constrain_similarities: true
     # let's handle low NLU confidence
   - name: FallbackClassifier
     threshold: 0.5
   #- name: RegexEntityExtractor
     #case_sensitive: False
     #use_lookup_table: True
     #use_regexes: True
     #use_word_boundaries: True
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
     constrain_similarities: true

# POLICIES

policies:
   - name: TEDPolicy
     max_history: 8
     epochs: 200
     constrain_similarities: true
   - name: AugmentedMemoizationPolicy
     max_history: 4
   - name: RulePolicy
     # let's handle low confidence actions
     core_fallback_threshold: 0.4
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
